import "server-only";

//Styles
import './globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css';

import NavBar from '@/components/app/navbar/NavBar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/app/footer/Footer'
import React, { useReducer } from 'react';
import { fstat } from 'fs';
import ParticleBackground from "@/components/app/ParticleBackground";
import AppReducer from '@/utils/reducers/AppReducer';
import { AppContextProvider } from '@/utils/contexts/AppContext';
import PageLoader from '@/components/app/PageLoader';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <React.StrictMode>
      <AppContextProvider>
        <html lang="en" >
          <body className={inter['className']}>
            <PageLoader />
            <NavBar />
            {children}
            <Footer />
            <ParticleBackground />
          </body>
        </html>
      </AppContextProvider>
    </React.StrictMode>
  )
}