import "server-only"

//Styles
import './globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css';

import NavBar from '@/components/app/navbar/NavBar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/app/footer/Footer'
import React from 'react';
import { fstat } from 'fs';
import ParticleBackground from "@/components/app/ParticleBackground";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {


  return (
    <html lang="en" >
      <body className={`${inter.className}`}>
        <React.StrictMode>
          <NavBar />
          {children}
          <Footer />
          <ParticleBackground />
        </React.StrictMode>
      </body>
    </html>
  )
}
